#!/bin/bash
#PBS -l nodes=6:ppn=12
#PBS -l walltime=00:05:00
#PBS -q batch
#PBS -N run_final
#PBS -j oe

cd ~/Final
#export COUNTER1=P_WALL_CLOCK_TIME
#export COUNTER2=PAPI_L1_DCM
mpiexec -np 6 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./parallel_code.x
